---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - '5.12'
  - '5.10'
cache:
  directories:
    - $HOME/perl5
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
  - cpanm Test::Memory::Cycle Test::Taint || true
script:
  - perl Makefile.PL && make
  - make TEST_VERBOSE=1 TEST_FILES='xt/author/live/*.t' test || true
  - perl -Ilib xt/author/live/*.t
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
